server:
  port: 8080
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/flowopendev
    username: developer
    password: developer
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
      mail:
        host: smtp.gmail.com
        port: 587
        username: f4kemailt3st@gmail.com
        password: pospmwcwuqdkjjhb
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true

---
environments: test
server:
  port: 3030
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: testdb
    password: psw1234
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database: H2
    show_sql: true
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.gmail.com
    port: 587
    username: f4kemailt3st@gmail.com
    password: pospmwcwuqdkjjhb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
